DB_DETAILS = {
    'dbname': 'drewf',
    'user': 'drewf',
    'password': 'Soccer.666',
    'host': 'localhost',
    'port': '5432'
}

TICKER_DICT = {
    'SPY': 'SPDR S&P 500 ETF Trust',
    'AAPL': 'Apple Inc.',
    'MSFT': 'Microsoft Corporation',
    'AMZN': 'Amazon.com, Inc.',
    'NVDA': 'NVIDIA Corporation',
    'GOOGL': 'Alphabet Inc. (Class A)',
    'META': 'Meta Platforms, Inc.',
    'TSLA': 'Tesla, Inc.',
    'UNH': 'UnitedHealth Group Incorporated',
    'JNJ': 'Johnson & Johnson',
    'XOM': 'Exxon Mobil Corporation',
    'JPM': 'JPMorgan Chase & Co.',
    'V': 'Visa Inc.',
    'PG': 'The Procter & Gamble Company',
    'HD': 'The Home Depot, Inc.',
    'MA': 'Mastercard Incorporated',
    'CVX': 'Chevron Corporation',
    'ABBV': 'AbbVie Inc.',
    'PEP': 'PepsiCo, Inc.',
    'KO': 'The Coca-Cola Company',
    'MRK': 'Merck & Co., Inc.',
    'COST': 'Costco Wholesale Corporation',
    'AVGO': 'Broadcom Inc.',
    'WMT': 'Walmart Inc.',
    'MCD': "McDonald's Corporation",
    'TMO': 'Thermo Fisher Scientific Inc.',
    'LIN': 'Linde plc',
    'AMD': 'Advanced Micro Devices, Inc.',
    'DIS': 'The Walt Disney Company',
    'ACN': 'Accenture plc',
    'NFLX': 'Netflix, Inc.',
    'ADP': 'Automatic Data Processing, Inc.',
    'INTU': 'Intuit Inc.',
    'AMGN': 'Amgen Inc.',
    'HON': 'Honeywell International Inc.',
    'IBM': 'International Business Machines Corporation',
    'GE': 'General Electric Company',
    'SBUX': 'Starbucks Corporation',
    'CAT': 'Caterpillar Inc.',
    'BA': 'The Boeing Company',
    'MMM': '3M Company',
    'AXP': 'American Express Company',
    'LOW': 'Lowe\'s Companies, Inc.',
    'GS': 'The Goldman Sachs Group, Inc.',
    'DE': 'Deere & Company',
    'BLK': 'BlackRock, Inc.',
    'SPGI': 'S&P Global Inc.',
    'MO': 'Altria Group, Inc.',
    'ELV': 'Elevance Health, Inc.',
    'CB': 'Chubb Limited',
    'AMT': 'American Tower Corporation',
    'C': 'Citigroup Inc.',
    'PGR': 'The Progressive Corporation',
    'NKE': 'NIKE, Inc.',
    'LMT': 'Lockheed Martin Corporation',
    'MDLZ': 'Mondelez International, Inc.',
    'ADI': 'Analog Devices, Inc.',
    'TGT': 'Target Corporation',
    'DHR': 'Danaher Corporation',
    'SYK': 'Stryker Corporation',
    'ISRG': 'Intuitive Surgical, Inc.',
    'ZTS': 'Zoetis Inc.',
    'CI': 'The Cigna Group',
    'GILD': 'Gilead Sciences, Inc.',
    'SCHW': 'The Charles Schwab Corporation',
    'PYPL': 'PayPal Holdings, Inc.',
    'USB': 'U.S. Bancorp',
    'SO': 'The Southern Company',
    'PLD': 'Prologis, Inc.',
    'ITW': 'Illinois Tool Works Inc.',
    'CL': 'Colgate-Palmolive Company',
    'ECL': 'Ecolab Inc.',
    'SHW': 'The Sherwin-Williams Company',
    'CHTR': 'Charter Communications, Inc.',
    'MMC': 'Marsh & McLennan Companies, Inc.',
    'APD': 'Air Products and Chemicals, Inc.',
    'TJX': 'The TJX Companies, Inc.',
    'BKNG': 'Booking Holdings Inc.',
    'EQIX': 'Equinix, Inc.',
    'FDX': 'FedEx Corporation',
    'AON': 'Aon plc',
    'EMR': 'Emerson Electric Co.',
    'NSC': 'Norfolk Southern Corporation',
    'ETN': 'Eaton Corporation plc',
    'D': 'Dominion Energy, Inc.',
    'DUK': 'Duke Energy Corporation',
    'NOC': 'Northrop Grumman Corporation',
    'KMB': 'Kimberly-Clark Corporation',
    'HUM': 'Humana Inc.',
    'TFC': 'Truist Financial Corporation',
    'CME': 'CME Group Inc.',
    'AEP': 'American Electric Power Company, Inc.',
    'WM': 'Waste Management, Inc.',
    'MCO': "Moody's Corporation",
    'MAR': 'Marriott International, Inc.',
    'ROP': 'Roper Technologies, Inc.',
    'AIG': 'American International Group, Inc.',
    'LHX': 'L3Harris Technologies, Inc.',
    'TRV': 'The Travelers Companies, Inc.',
    'HCA': 'HCA Healthcare, Inc.',
    'ED': 'Consolidated Edison, Inc.',
    'PSA': 'Public Storage',
    'CMCSA': 'Comcast Corporation',
    'COP': 'ConocoPhillips',
    'EXC': 'Exelon Corporation',
    'VLO': 'Valero Energy Corporation',
    'ORCL': 'Oracle Corporation',
    'KMI': 'Kinder Morgan, Inc.',
    'PPL': 'PPL Corporation',
    'PEG': 'Public Service Enterprise Group Incorporated',
    'OXY': 'Occidental Petroleum Corporation',
    'WEC': 'WEC Energy Group, Inc.',
    'EIX': 'Edison International',
    'PCG': 'PG&E Corporation',
    'DTE': 'DTE Energy Company',
    'AES': 'The AES Corporation',
    'CMS': 'CMS Energy Corporation',
    'AEE': 'Ameren Corporation',
    'NI': 'NiSource Inc.',
    'LNT': 'Alliant Energy Corporation',
    'ES': 'Eversource Energy',
    'FE': 'FirstEnergy Corp.',
    'NEE': 'NextEra Energy, Inc.',
    'PNW': 'Pinnacle West Capital Corporation',
    'CNP': 'CenterPoint Energy, Inc.',
    'ATO': 'Atmos Energy Corporation',
    'SRE': 'Sempra'
}

TICKER_TO_DOMAIN = {
    "SPY": "spdrs.com",
    "AAPL": "apple.com",
    "MSFT": "microsoft.com",
    "AMZN": "amazon.com",
    "NVDA": "nvidia.com",
    "GOOGL": "abc.xyz",
    "META": "meta.com",
    "TSLA": "tesla.com",
    "UNH": "unitedhealthgroup.com",
    "JNJ": "jnj.com",
    "XOM": "corporate.exxonmobil.com",
    "JPM": "jpmorganchase.com",
    "V": "visa.com",
    "PG": "pg.com",
    "HD": "homedepot.com",
    "MA": "mastercard.com",
    "CVX": "chevron.com",
    "ABBV": "abbvie.com",
    "PEP": "pepsico.com",
    "KO": "coca-colacompany.com",
    "MRK": "merck.com",
    "COST": "costco.com",
    "AVGO": "broadcom.com",
    "WMT": "walmart.com",
    "MCD": "mcdonalds.com",
    "TMO": "thermofisher.com",
    "LIN": "linde.com",
    "AMD": "amd.com",
    "DIS": "thewaltdisneycompany.com",
    "ACN": "accenture.com",
    "NFLX": "netflix.com",
    "ADP": "adp.com",
    "INTU": "intuit.com",
    "AMGN": "amgen.com",
    "HON": "honeywell.com",
    "IBM": "ibm.com",
    "GE": "ge.com",
    "SBUX": "starbucks.com",
    "CAT": "caterpillar.com",
    "BA": "boeing.com",
    "MMM": "mmm.com",
    "AXP": "americanexpress.com",
    "LOW": "lowes.com",
    "GS": "goldmansachs.com",
    "DE": "deere.com",
    "BLK": "blackrock.com",
    "SPGI": "spglobal.com",
    "MO": "altria.com",
    "ELV": "elevancehealth.com",
    "CB": "chubb.com",
    "AMT": "americantower.com",
    "C": "citigroup.com",
    "PGR": "progressive.com",
    "NKE": "nike.com",
    "LMT": "lockheedmartin.com",
    "MDLZ": "mondelezinternational.com",
    "ADI": "analog.com",
    "TGT": "target.com",
    "DHR": "danaher.com",
    "SYK": "stryker.com",
    "ISRG": "intuitive.com",
    "ZTS": "zoetis.com",
    "CI": "cigna.com",
    "GILD": "gilead.com",
    "SCHW": "schwab.com",
    "PYPL": "paypal.com",
    "USB": "usbank.com",
    "SO": "southerncompany.com",
    "PLD": "prologis.com",
    "ITW": "itw.com",
    "CL": "colgatepalmolive.com",
    "ECL": "ecolab.com",
    "SHW": "sherwin-williams.com",
    "CHTR": "charter.com",
    "MMC": "mmc.com",
    "APD": "airproducts.com",
    "TJX": "tjx.com",
    "BKNG": "booking.com",
    "EQIX": "equinix.com",
    "FDX": "fedex.com",
    "AON": "aon.com",
    "EMR": "emerson.com",
    "NSC": "nscorp.com",
    "ETN": "eaton.com",
    "D": "dominionenergy.com",
    "DUK": "duke-energy.com",
    "NOC": "northropgrumman.com",
    "KMB": "kimberly-clark.com",
    "HUM": "humana.com",
    "TFC": "truist.com",
    "CME": "cmegroup.com",
    "AEP": "aep.com",
    "WM": "wm.com",
    "MCO": "moodys.com",
    "MAR": "marriott.com",
    "ROP": "ropertech.com",
    "AIG": "aig.com",
    "LHX": "lharris.com",
    "TRV": "travellers.com",
    "HCA": "hcahealthcare.com",
    "ED": "coned.com",
    "PSA": "publicstorage.com",
    "CMCSA": "comcast.com",
    "COP": "conocophillips.com",
    "EXC": "exelon.com",
    "VLO": "valero.com",
    "ORCL": "oracle.com",
    "KMI": "kindermorgan.com",
    "PPL": "pplweb.com",
    "PEG": "pseg.com",
    "OXY": "oxy.com",
    "WEC": "wecenergygroup.com",
    "EIX": "edison.com",
    "PCG": "pge.com",
    "DTE": "dteenergy.com",
    "AES": "aes.com",
    "CMS": "cmsenergy.com",
    "AEE": "ameren.com",
    "NI": "nisource.com",
    "LNT": "alliantenergy.com",
    "ES": "eversource.com",
    "FE": "firstenergycorp.com",
    "NEE": "nexteraenergy.com",
    "PNW": "pinnaclewest.com",
    "CNP": "centerpointenergy.com",
    "ATO": "atmosenergy.com",
    "SRE": "sempra.com"
}

STOCK_CATEGORIES = {
    'Tech': [
        'AAPL', 'MSFT', 'NVDA', 'GOOGL', 'META', 'AVGO', 'AMD', 'ACN', 
        'ADP', 'INTU', 'HON', 'IBM', 'GE', 'CAT', 'BA', 'MMM', 'AMT', 
        'ADI', 'ITW', 'ECL', 'CHTR', 'EQIX', 'EMR', 'NSC', 'ETN', 'LMT', 
        'ECL', 'ROP', 'LHX', 'WM', 'ORCL'
    ],
    'Finance': [
        'SPY', 'JPM', 'V', 'MA', 'AXP', 'GS', 'BLK', 'SPGI', 'CB', 'C', 
        'PGR', 'SCHW', 'PYPL', 'USB', 'PLD', 'MMC', 'AON', 'TFC', 'CME', 
        'MCO', 'AIG', 'TRV', 'PSA'
    ],
    'Healthcare': [
        'UNH', 'JNJ', 'ABBV', 'MRK', 'TMO', 'AMGN', 'DHR', 'SYK', 'ISRG', 
        'ZTS', 'CI', 'GILD', 'ELV', 'HUM', 'HCA'
    ],
    'Energy': [
        'XOM', 'CVX', 'LIN', 'SO', 'APD', 'D', 'DUK', 'AEP', 'ED', 'COP', 
        'EXC', 'VLO', 'KMI', 'PPL', 'PEG', 'OXY', 'WEC', 'EIX', 'PCG', 
        'DTE', 'AES', 'CMS', 'AEE', 'NI', 'LNT', 'ES', 'FE', 'NEE', 'PNW', 
        'CNP', 'ATO', 'SRE'
    ],
    'Retail': [
        'AMZN', 'PG', 'HD', 'PEP', 'KO', 'COST', 'WMT', 'MCD', 'SBUX', 
        'LOW', 'MO', 'MDLZ', 'TGT', 'CL', 'SHW', 'TJX', 'BKNG', 'FDX', 
        'KMB', 'MAR'
    ],
    'Sports': [
        'NKE'
    ],
    'Entertainment': [
        'DIS', 'NFLX', 'CMCSA'
    ],
    'Startups': [
        'TSLA'
    ]
}
